name: 'benchod847'
description: 'A GitHub Action for activating and using various coding agents like Amp and Claude with configurable models and trigger words'
author: 'Ivan Leo'
icon: activity
inputs:
  agent:
    description: 'Which coding agent to use (amp, claude, etc.)'
    required: false
    default: 'amp'
  model:
    description: 'Model to use for the agent'
    required: false
    default: 'claude-3-sonnet'
  trigger-word:
    description: 'Trigger word to activate the agent'
    required: false
    default: '@agent'
outputs:
  result:
    description: 'Result from the coding agent'
runs:
  using: 'node20'
  main: 'dist/index.js'
